name = "Abyssal Skies"
author = "Halcyon Development"
version = "0.0.1a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e6efa06a608667d653510af55ef8f39fa8d1001de6d7869203d99df446a5733"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"

[options]
no-internal-hashes = true
