name = "Abyssal Skies"
author = "Halcyon Development"
version = "0.0.1a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f868f36f4c7898e0df925f2ef0dd1ca0c3b20b87a59732b42d12c99feecf89de"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"

[options]
no-internal-hashes = true
