name = "Abyssal Skies"
author = "Halcyon Development"
version = "0.0.1a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4560b835811ea3702ef083d6f6f045115355310f00613bafc5024e79c0f64965"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"

[options]
no-internal-hashes = true
